name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - uses: astral-sh/setup-uv@v6

      # Run all hooks EXCEPT mypy (which needs the built package)
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    needs: [pre-commit]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        runs-on: [ubuntu-latest]

    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v6

      - name: Install package
        env:
          SCCACHE_GHA_ENABLED: "true"
        run: uv sync -v

      - name: Run mypy
        run: uv run pre-commit run mypy --all-files --hook-stage manual

      - name: Test package
        run: uv run pytest -s
